services:
  discord-bot:
    build: .
    environment:
      - GROQ_API_KEY: ReplaceWithYourGroqKey
      - DISCORD_TOKEN: ReplaceWithYourToken
      - HF_TOKEN: ReplaceWithYourHuggingFaceToken
    container_name: lappland
    restart: unless-stopped
    volumes:
      - ./app:/app