services:
  discord-bot:
    build: .
    environment:
      - GROQ_API_KEY: ReplaceWithYourGroqKey
      - DISCORD_TOKEN: ReplaceWithYourToken
      - FAL_TOKEN: ReplaceWithYourFalToken
      - PYTHONUNBUFFERED: 1
    container_name: lappland
    restart: unless-stopped
    volumes:
      - ./app:/app

  oauth:
    build:
      context: .
      dockerfile: Dockerfile.oauth
    container_name: lappland-spotify-oauth
    restart: unless-stopped
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data